name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  All:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.1

      - name: Install dependencies
        run: brew install ripgrep golangci-lint golines

      - name: Forbid
        run: ./bin/forbid

      - name: Format
        run: gofmt -l .

      - name: Lint
        run: golangci-lint run ./src

      - name: Test
        run: go test -v ./src
